# Generated by Django 4.2.5 on 2023-10-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_ambiente_alter_docente_nome_alter_docente_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('etiqueta', models.CharField(max_length=50)),
                ('diasemana', models.CharField(max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.ambiente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.turma')),
            ],
        ),
    ]
