# Generated by Django 4.2.5 on 2023-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='diasemana',
            field=models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=20),
        ),
    ]
