# Generated by Django 4.2.5 on 2023-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_alter_evento_diasemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='diasemana',
            field=models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], default='Segunda', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='etiqueta',
            field=models.CharField(choices=[('Verde', '#70a288b0'), ('Amarelo', '#dab785b0'), ('Vermelho', '#d5896fb0')], default='Verde', max_length=50),
        ),
    ]
