# Generated by Django 4.2.5 on 2023-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_evento_diasemana_alter_evento_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='etiqueta',
            field=models.CharField(choices=[('#70a288b0', 'Verde'), ('#dab785b0', 'Amarelo'), ('#d5896fb0', 'Vermelho')], default='Verde', max_length=50),
        ),
    ]
