# Generated by Django 4.2.5 on 2023-10-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_alter_evento_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.ambiente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.docente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.turma'),
        ),
    ]
